{
 "title": "nividia-cuda-exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_temperature_celsius{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Usage %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_utilization_gpu_percent{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Memory %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_utilization_memory_percent{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_fan_speed_percent{instance=\"nvidia-cuda-exporter:8888\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cuda Core %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cuda_cores_used_percent{instance=\"nvidia-cuda-exporter:8888\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "GPU Clock MHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    { "expr": "gpu_clock_graphics_mhz{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "gpu_clock_memory_mhz{instance=\"nvidia-cuda-exporter:8888\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIE RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mflops" } },
   "targets": [
    {
     "expr": "gpu_pcie_tx_mb{job=\"nvidia-cuda-exporter\"} /10",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_pcie_rx_mb{job=\"nvidia-cuda-exporter\"} /10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    { "expr": "gpu_memory_used_mb{} / 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_power_draw_watts{job=\"nvidia-cuda-exporter\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}